import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <h3 style={{ textAlign: "center", paddingTop: "5%" }}>Welcome to my page</h3>
              <br></br>
              <div style={{ display: "flex", justifyContent: "center", alignContent: "center" }}>
                <h1 style={{ textAlign: "center", paddingTop: "5%", width: "50%" }}> This is a simple project that works with next.js, clerk, middleware, and prisma to simulate an extremely simple posting &quot;blog&quot; site.</h1>
              </div>
              <div style={{ textAlign: "center", paddingTop: "5%" }}>
                <SignInButton>
                  <div style={{ textAlign: "center", paddingTop: "5%" }}>
                    <Button>Sign In / Create Account</Button>
                  </div>
                </SignInButton>
              </div>
            </SignedOut>
            <SignedIn>
              <main>{children}</main>
              <div style={{ position: "absolute", top: "0", right: "0", paddingTop: "5%", paddingRight: "5%" }}>
                <UserButton />
              </div>
            </SignedIn>
          </header>
        </body>
      </html>
    </ClerkProvider>
  );
}
