import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
          <h3 style={{ textAlign: "center", paddingTop: "5%" }}>Welcome to my page</h3>
          <br></br>
          <h1 style={{ textAlign: "center", paddingTop: "5%" }}> This is a simple project that works with next.js, clerk, middleware, and prisma to simulate an extremely simple posting &quot;blog&quot; site.</h1>
          <SignedOut>
            <div style={{ textAlign: "center", paddingTop: "5%" }}>
              <SignInButton>
                <div style={{ textAlign: "center", paddingTop: "5%" }}>
                  <Button>Sign In</Button>
                </div>
              </SignInButton>
            </div>
            <div style={{ textAlign: "center", paddingTop: "5%" }}>
              Or
              <div style={{ textAlign: "center", paddingTop: "5%", display: "flex", justifyContent: "center", alignItems: "center"}}>
              </div>
            </div>
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          </header>
          <main>{children}</main>
        </body>
      </html>
      </ClerkProvider>
  );
}
